import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Main from "../components/Main";
import Swap from "../components/Form/Swap";
const Home: NextPage = () => {
  return (
      <>
		<Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

		<Header />

      <Main />

      <Footer />
		</>
  );
};

export default Home;
